trigger:
- master

jobs:
- job: Pack
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: NodeTool@0
    displayName: 'Install Node 11.x'
    inputs:
      versionSpec: 11.x
  - task: Npm@1
    displayName: 'npm pack'
    inputs:
      command: custom
      verbose: false
      customCommand: pack
  - task: CopyFiles@2
    displayName: 'Copy Files to: drop'
    inputs:
      Contents: '*.tgz'
      TargetFolder: drop
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.SourcesDirectory)/drop
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.SourcesDirectory)/dist
      artifactName: dist
- job: Test
  pool:
    vmImage: 'Ubuntu 16.04'
  strategy:
    matrix:
      Node6:
        node.version: 6.x
      Node8:
        node.version: 8.x
      Node10:
        node.version: 10.x
      Node11:
        node.version: 11.x
  dependsOn: Pack
  condition: succeeded()
  steps:
  - script: 'sudo apt-get update'
    displayName: 'sudo apt-get update'
  - script: 'sudo apt install chromium-browser'
    displayName: 'sudo apt install chromium-browser'
  - task: NodeTool@0
    displayName: 'Install Node $(node.version)'
    inputs:
      versionSpec: $(node.version)
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      verbose: false
  - task: DownloadBuildArtifacts@0
    displayName: 'Download Build Artifacts'
    inputs:
      artifactName: dist
      downloadPath: $(System.DefaultWorkingDirectory)
  - task: Npm@1
    displayName: 'npm test'
    inputs:
      command: custom
      verbose: false
      customCommand: test
