trigger:
- master

jobs:
- job: Check_Everything
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      command: custom
      verbose: false
      customCommand: install
  - task: Npm@1
    displayName: 'npm run check:everything -- --azure-devops'
    inputs:
      command: custom
      verbose: false
      customCommand: run check:everything -- --azure-devops
- job: Pack
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: NodeTool@0
    displayName: 'Install Node 11.x'
    inputs:
      versionSpec: 11.x
  - task: Npm@1
    displayName: 'npm pack'
    inputs:
      command: custom
      verbose: false
      customCommand: pack
  - task: CopyFiles@2
    displayName: 'Copy Files to: drop'
    inputs:
      Contents: '*.tgz'
      TargetFolder: drop
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.SourcesDirectory)/drop
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.SourcesDirectory)/dist
      artifactName: dist
- template: azure-pipelines-job.yml
  parameters:
    nodeVersion: '6'
- template: azure-pipelines-job.yml
  parameters:
    nodeVersion: '8'
- template: azure-pipelines-job.yml
  parameters:
    nodeVersion: '10'
- template: azure-pipelines-job.yml
  parameters:
    nodeVersion: '11'
- job: Test_dependent_projects
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      command: custom
      verbose: false
      customCommand: install
  - task: Npm@1
    displayName: 'npm build'
    inputs:
      command: custom
      verbose: false
      customCommand: build
  - task: Npm@1
    displayName: 'npm run dep:ms-rest-azure-js'
    inputs:
      command: custom
      verbose: true
      customCommand: run dep:ms-rest-azure-js
  - task: Npm@1
    displayName: 'Build ms-rest-azure-js'
    inputs:
      command: 'custom'
      workingDir: '../.tmp/ms-rest-azure-js'
      customCommand: 'build'
  - task: Npm@1
    displayName: 'Test ms-rest-azure-js'
    inputs:
      command: 'custom'
      workingDir: '../.tmp/ms-rest-azure-js'
      customCommand: 'test'
  - task: Npm@1
    displayName: 'npm run dep:autorest.typescript'
    inputs:
      command: custom
      verbose: true
      customCommand: run dep:autorest.typescript
  - task: Npm@1
    displayName: 'Test autorest.typescript'
    inputs:
      command: 'custom'
      workingDir: '../.tmp/autorest.typescript'
      customCommand: 'test'
