jobs:
- job: Check_Everything
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      command: custom
      verbose: false
      customCommand: install
  - task: Npm@1
    displayName: 'npm run check:everything -- --azure-devops'
    inputs:
      command: custom
      verbose: false
      customCommand: run check:everything -- --azure-devops
- template: azure-pipelines-test.yml
  parameters:
    nodeVersion: '10'
- template: azure-pipelines-test.yml
  parameters:
    nodeVersion: '12'
