trigger:
- master

pr: none

jobs:
- job: Build
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      command: custom
      verbose: false
      customCommand: install
  - task: Npm@1
    displayName: 'npm run build'
    inputs:
      command: custom
      verbose: false
      customCommand: run build
- job: Pack
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: NodeTool@0
    displayName: 'Install Node 11.x'
    inputs:
      versionSpec: 11.x
  - task: Npm@1
    displayName: 'npm pack'
    inputs:
      command: custom
      verbose: false
      customCommand: pack
  - task: CopyFiles@2
    displayName: 'Copy Files to: drop'
    inputs:
      Contents: '*.tgz'
      TargetFolder: drop
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.SourcesDirectory)/drop
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.SourcesDirectory)/dist
      artifactName: dist
- template: azure-pipelines-test.yml
  parameters:
    nodeVersion: '10'
- template: azure-pipelines-test.yml
  parameters:
    nodeVersion: '12'
